# Import types
from typing import Optional, List, Dict, Any
from pydantic import BaseModel

"""
This file contains all the base-level models that are directly accessed in the Document.
"""

from .automod import automoderatorModules, automoderatorSettings, automodRule
from .history import HistoryCase
from .logging import loggingSettings
from .starboard import StarboardMessage
from .server import serverBan, serverMute, serverRoles, serverSettings


# RSS
class RSSFeed(BaseModel):
    """
    - channelId - `str` - The channel id
    - feedURL - `str` - The feed's URL
    - last_checked - `tuple` - When last checked. See: https://feedparser.readthedocs.io/en/latest/date-parsing.html
    """

    channelId: str
    feedURL: str
    last_checked: Optional[tuple] = None


# Starboard
class Starboard(BaseModel):
    """
    - channelId - `str` - The channel id
    - minimum - `int` - The minimum amount of emote to be added to starboard. Defaults to 3
    - emote - `int` - The emote's ID, defaulting to the Star emoji. ⭐
    - messages - `List[StarboardMessage]` - A list of starboard messages. This way, when a star is added we can count and edit message.
    """

    channelId: str
    minimum: int = 3
    emote: int = 90001779
    messages: List[StarboardMessage] = list()


# Server member data
class serverMember(BaseModel):
    """
    - member - `str` - The member's ID
    - history - `Dict[str, HistoryCase]` - The user's history of cases.

    # TODO: tempmute and tempban durations here
    """

    member: str
    history: Dict[str, HistoryCase] = dict()


# Server data
class serverData(BaseModel):
    """
    - automodRules - `List[automodRule]` - The server's automod rules
    - automodSettings - `automoderatorSettings` - Automod settings
    - automodModules - `automoderatorModules` - Automod default modules
    - settings - `serverSettings` - The server's settings.
    - mutes - `List[serverMute]` - The server's current saved mutes.
    - bans - `List[serverBan]` - The server's current saved bans.
    """

    automodRules: List[automodRule] = list()

    automodSettings: automoderatorSettings = automoderatorSettings()

    automodModules: automoderatorModules = automoderatorModules()

    settings: serverSettings = serverSettings()

    mutes: List[serverMute] = list()

    bans: List[serverBan] = list()


# Logging
class loggingChannels(BaseModel):
    """
    - logSettings - `loggingSettings` - Server logging settings
    - setChannels - `dict` - Every logging channel. Prevents a logging channel from being set multiple times. (key (channel id): eventType)

    - allEvents - `list[str]` - All events

    - allChannelEvents - `list[str]` - All channel related events (documentUpdate, announcementUpdate, forumUpdate, calendarUpdate, channelStateUpdate)
    - allMemberEvents - `list[str]` - All member related events (membershipChange, memberUpdate)

    - membershipChange - `list[str]` - Membership related events. (Joins/Leaves/Kicks/Bans)
    - memberUpdate - `list[str]` - Member update related events (nickname, roles)

    - automod - `list[str]` - Moderation actions generated by the AutoMod.
    - messageChange -` list[str]` - message updated/deleted
    - moderatorAction - `list[str]` - moderator made an action
    - botSettingChanges - `list[str]` - Bot setting was changed

    - channelStateUpdate - `list[str]` - Channel state changes.
    - forumUpdate - `list[str]` - Forum post was updated
    - documentUpdate - `list[str]` - Document was updated
    - announcementUpdate - `list[str]` - Announcement was updated
    - listUpdate - `list[str]` - List was updated
    - categoryUpdate - `list[str]` - Category was updated
    """

    logSettings: loggingSettings = loggingSettings()

    setChannels: dict = {}

    allEvents: List[str] = list()

    allChannelEvents: List[str] = list()

    allMemberEvents: List[str] = list()

    membershipChange: List[str] = list()

    memberUpdate: List[str] = list()

    automod: List[str] = list()

    botSettingChanges: List[str] = list()

    messageChange: List[str] = list()

    moderatorAction: List[str] = list()

    channelStateUpdate: List[str] = list()

    forumUpdate: List[str] = list()

    documentUpdate: List[str] = list()

    announcementUpdate: List[str] = list()

    calendarUpdate: List[str] = list()

    listUpdate: List[str] = list()

    categoryUpdate: List[str] = list()


# Channels
class chaChannel(BaseModel):
    """
    - enabled - `bool` - Whether this channel is enabled
    - channelId - `str` - The channel's ID
    - metadata - `Dict[str, Any]` - The channel data
    - channelType - `str` - The channel type
    """

    enabled: bool = True
    channelId: str
    data: Dict[str, Any]
    channelType: str
